export const bankConstants = {
    SET_LOADING_STATUS: 'SET_LOADING_STATUS',
    SET_ERROR: "SET_ERROR",

    GET_ALL_BANKS_SUCCESS: 'GET_ALL_BANKS_SUCCESS',
    DELETE_BANK_SUCCESS: 'DELETE_BANK_SUCCESS',
    CREATE_BANK_SUCCESS: 'CREATE_BANK_SUCCESS',
    UPDATE_BANK_SUCCESS: 'UPDATE_BANK_SUCCESS'
}